/**
 * Plan de cuentas estándar para clínicas/empresas de servicios médicos en Ecuador.
 * Basado en el catálogo NIIF para PYMES de la Superintendencia de Compañías.
 * (Cuentas más comunes; el usuario puede agregar / editar libremente.)
 */
module.exports = [
  // ACTIVO
  { code: '1',        name: 'ACTIVO',                                     type: 'ACTIVO',    nature: 'DEBITO',  allowsMovement: false },
  { code: '1.1',      name: 'ACTIVO CORRIENTE',                           type: 'ACTIVO',    nature: 'DEBITO',  allowsMovement: false },
  { code: '1.1.01',   name: 'EFECTIVO Y EQUIVALENTES DE EFECTIVO',        type: 'ACTIVO',    nature: 'DEBITO',  allowsMovement: false },
  { code: '1.1.01.01',name: 'Caja general',                               type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.1.01.02',name: 'Caja chica',                                 type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.1.01.03',name: 'Bancos',                                     type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.1.02',   name: 'CUENTAS POR COBRAR',                         type: 'ACTIVO',    nature: 'DEBITO',  allowsMovement: false },
  { code: '1.1.02.01',name: 'Clientes',                                   type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.1.02.02',name: 'Tarjetas de crédito por liquidar',           type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.1.02.03',name: 'Anticipos a proveedores',                    type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.1.02.04',name: 'Préstamos a empleados',                      type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.1.02.05',name: 'Provisión cuentas incobrables',              type: 'ACTIVO',    nature: 'CREDITO' },
  { code: '1.1.03',   name: 'CRÉDITO TRIBUTARIO',                         type: 'ACTIVO',    nature: 'DEBITO',  allowsMovement: false },
  { code: '1.1.03.01',name: 'IVA en compras',                             type: 'ACTIVO',    nature: 'DEBITO',  taxCode: 'IVA_COMPRAS' },
  { code: '1.1.03.02',name: 'Retención IVA por cobrar',                   type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.1.03.03',name: 'Retención Renta por cobrar',                 type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.1.03.04',name: 'Anticipo Impuesto a la Renta',               type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.1.04',   name: 'INVENTARIOS',                                type: 'ACTIVO',    nature: 'DEBITO',  allowsMovement: false },
  { code: '1.1.04.01',name: 'Inventario de productos',                    type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.1.04.02',name: 'Inventario de insumos médicos',              type: 'ACTIVO',    nature: 'DEBITO' },

  { code: '1.2',      name: 'ACTIVO NO CORRIENTE',                        type: 'ACTIVO',    nature: 'DEBITO',  allowsMovement: false },
  { code: '1.2.01',   name: 'PROPIEDAD PLANTA Y EQUIPO',                  type: 'ACTIVO',    nature: 'DEBITO',  allowsMovement: false },
  { code: '1.2.01.01',name: 'Terrenos',                                   type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.2.01.02',name: 'Edificios',                                  type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.2.01.03',name: 'Muebles y enseres',                          type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.2.01.04',name: 'Equipo de oficina',                          type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.2.01.05',name: 'Equipo médico',                              type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.2.01.06',name: 'Equipo de cómputo',                          type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.2.01.07',name: 'Vehículos',                                  type: 'ACTIVO',    nature: 'DEBITO' },
  { code: '1.2.02',   name: 'DEPRECIACIÓN ACUMULADA',                     type: 'ACTIVO',    nature: 'CREDITO', allowsMovement: false },
  { code: '1.2.02.01',name: '(-) Depreciación acumulada edificios',       type: 'ACTIVO',    nature: 'CREDITO' },
  { code: '1.2.02.02',name: '(-) Depreciación acumulada muebles',         type: 'ACTIVO',    nature: 'CREDITO' },
  { code: '1.2.02.03',name: '(-) Depreciación acumulada equipo oficina',  type: 'ACTIVO',    nature: 'CREDITO' },
  { code: '1.2.02.04',name: '(-) Depreciación acumulada equipo médico',   type: 'ACTIVO',    nature: 'CREDITO' },
  { code: '1.2.02.05',name: '(-) Depreciación acumulada equipo cómputo',  type: 'ACTIVO',    nature: 'CREDITO' },
  { code: '1.2.02.06',name: '(-) Depreciación acumulada vehículos',       type: 'ACTIVO',    nature: 'CREDITO' },

  // PASIVO
  { code: '2',        name: 'PASIVO',                                     type: 'PASIVO',    nature: 'CREDITO', allowsMovement: false },
  { code: '2.1',      name: 'PASIVO CORRIENTE',                           type: 'PASIVO',    nature: 'CREDITO', allowsMovement: false },
  { code: '2.1.01',   name: 'CUENTAS POR PAGAR',                          type: 'PASIVO',    nature: 'CREDITO', allowsMovement: false },
  { code: '2.1.01.01',name: 'Proveedores locales',                        type: 'PASIVO',    nature: 'CREDITO' },
  { code: '2.1.01.02',name: 'Cuentas por pagar empleados',                type: 'PASIVO',    nature: 'CREDITO' },
  { code: '2.1.01.03',name: 'Anticipos de clientes',                      type: 'PASIVO',    nature: 'CREDITO' },
  { code: '2.1.02',   name: 'OBLIGACIONES FISCALES',                      type: 'PASIVO',    nature: 'CREDITO', allowsMovement: false },
  { code: '2.1.02.01',name: 'IVA en ventas',                              type: 'PASIVO',    nature: 'CREDITO', taxCode: 'IVA_VENTAS' },
  { code: '2.1.02.02',name: 'IVA por pagar',                              type: 'PASIVO',    nature: 'CREDITO' },
  { code: '2.1.02.03',name: 'Retención IVA por pagar',                    type: 'PASIVO',    nature: 'CREDITO' },
  { code: '2.1.02.04',name: 'Retención Renta por pagar',                  type: 'PASIVO',    nature: 'CREDITO' },
  { code: '2.1.02.05',name: 'Impuesto a la Renta por pagar',              type: 'PASIVO',    nature: 'CREDITO' },
  { code: '2.1.03',   name: 'OBLIGACIONES LABORALES',                     type: 'PASIVO',    nature: 'CREDITO', allowsMovement: false },
  { code: '2.1.03.01',name: 'Sueldos por pagar',                          type: 'PASIVO',    nature: 'CREDITO' },
  { code: '2.1.03.02',name: 'IESS por pagar',                             type: 'PASIVO',    nature: 'CREDITO' },
  { code: '2.1.03.03',name: 'Décimo tercer sueldo por pagar',             type: 'PASIVO',    nature: 'CREDITO' },
  { code: '2.1.03.04',name: 'Décimo cuarto sueldo por pagar',             type: 'PASIVO',    nature: 'CREDITO' },
  { code: '2.1.03.05',name: 'Fondos de reserva por pagar',                type: 'PASIVO',    nature: 'CREDITO' },
  { code: '2.1.03.06',name: 'Vacaciones por pagar',                       type: 'PASIVO',    nature: 'CREDITO' },
  { code: '2.1.03.07',name: 'Participación trabajadores 15%',             type: 'PASIVO',    nature: 'CREDITO' },
  { code: '2.1.04',   name: 'OBLIGACIONES BANCARIAS CORRIENTES',          type: 'PASIVO',    nature: 'CREDITO' },

  { code: '2.2',      name: 'PASIVO NO CORRIENTE',                        type: 'PASIVO',    nature: 'CREDITO', allowsMovement: false },
  { code: '2.2.01',   name: 'Préstamos bancarios largo plazo',            type: 'PASIVO',    nature: 'CREDITO' },

  // PATRIMONIO
  { code: '3',        name: 'PATRIMONIO',                                 type: 'PATRIMONIO',nature: 'CREDITO', allowsMovement: false },
  { code: '3.1',      name: 'CAPITAL',                                    type: 'PATRIMONIO',nature: 'CREDITO', allowsMovement: false },
  { code: '3.1.01',   name: 'Capital social',                             type: 'PATRIMONIO',nature: 'CREDITO' },
  { code: '3.2',      name: 'RESERVAS',                                   type: 'PATRIMONIO',nature: 'CREDITO', allowsMovement: false },
  { code: '3.2.01',   name: 'Reserva legal',                              type: 'PATRIMONIO',nature: 'CREDITO' },
  { code: '3.3',      name: 'RESULTADOS',                                 type: 'PATRIMONIO',nature: 'CREDITO', allowsMovement: false },
  { code: '3.3.01',   name: 'Resultados acumulados',                      type: 'PATRIMONIO',nature: 'CREDITO' },
  { code: '3.3.02',   name: 'Resultado del ejercicio',                    type: 'PATRIMONIO',nature: 'CREDITO' },

  // INGRESOS
  { code: '4',        name: 'INGRESOS',                                   type: 'INGRESO',   nature: 'CREDITO', allowsMovement: false },
  { code: '4.1',      name: 'INGRESOS OPERACIONALES',                     type: 'INGRESO',   nature: 'CREDITO', allowsMovement: false },
  { code: '4.1.01',   name: 'Ingresos por servicios médicos',             type: 'INGRESO',   nature: 'CREDITO' },
  { code: '4.1.02',   name: 'Ingresos por venta de productos',            type: 'INGRESO',   nature: 'CREDITO' },
  { code: '4.1.03',   name: 'Descuentos en ventas',                       type: 'INGRESO',   nature: 'DEBITO' },
  { code: '4.1.04',   name: 'Devoluciones en ventas',                     type: 'INGRESO',   nature: 'DEBITO' },
  { code: '4.2',      name: 'INGRESOS NO OPERACIONALES',                  type: 'INGRESO',   nature: 'CREDITO', allowsMovement: false },
  { code: '4.2.01',   name: 'Intereses ganados',                          type: 'INGRESO',   nature: 'CREDITO' },
  { code: '4.2.02',   name: 'Otros ingresos',                             type: 'INGRESO',   nature: 'CREDITO' },

  // COSTO
  { code: '5',        name: 'COSTOS',                                     type: 'COSTO',     nature: 'DEBITO',  allowsMovement: false },
  { code: '5.1.01',   name: 'Costo de venta de productos',                type: 'COSTO',     nature: 'DEBITO' },
  { code: '5.1.02',   name: 'Costo de servicios prestados',               type: 'COSTO',     nature: 'DEBITO' },
  { code: '5.1.03',   name: 'Insumos médicos consumidos',                 type: 'COSTO',     nature: 'DEBITO' },

  // GASTOS
  { code: '6',        name: 'GASTOS',                                     type: 'GASTO',     nature: 'DEBITO',  allowsMovement: false },
  { code: '6.1',      name: 'GASTOS ADMINISTRATIVOS',                     type: 'GASTO',     nature: 'DEBITO',  allowsMovement: false },
  { code: '6.1.01',   name: 'Sueldos y salarios',                         type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.02',   name: 'Beneficios sociales',                        type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.03',   name: 'Aporte patronal IESS',                       type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.04',   name: 'Décimo tercero (gasto)',                     type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.05',   name: 'Décimo cuarto (gasto)',                      type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.06',   name: 'Fondos de reserva (gasto)',                  type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.07',   name: 'Vacaciones (gasto)',                         type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.08',   name: 'Honorarios profesionales',                   type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.09',   name: 'Arriendos',                                  type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.10',   name: 'Servicios básicos',                          type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.11',   name: 'Suministros de oficina',                     type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.12',   name: 'Mantenimiento y reparaciones',               type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.13',   name: 'Depreciación PPE',                           type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.14',   name: 'Combustibles y lubricantes',                 type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.15',   name: 'Publicidad y marketing',                     type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.16',   name: 'Comisiones bancarias',                       type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.17',   name: 'Comisiones tarjeta de crédito',              type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.18',   name: 'Impuestos y contribuciones',                 type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.19',   name: 'Gastos de viaje',                            type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.20',   name: 'Capacitación',                               type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.1.99',   name: 'Otros gastos administrativos',               type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.2',      name: 'GASTOS FINANCIEROS',                         type: 'GASTO',     nature: 'DEBITO',  allowsMovement: false },
  { code: '6.2.01',   name: 'Intereses pagados',                          type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.3',      name: 'GASTOS NO DEDUCIBLES',                       type: 'GASTO',     nature: 'DEBITO',  allowsMovement: false },
  { code: '6.3.01',   name: 'Multas e intereses tributarios',             type: 'GASTO',     nature: 'DEBITO' },
  { code: '6.3.02',   name: 'Gastos personales no deducibles',            type: 'GASTO',     nature: 'DEBITO' },
];
